version: 0.0
os: linux
files:
  - source: /chatapplication
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: install_dependancies
      timeout: 300
    - location: env
      timeout: 300
    - location: automate
      timeout: 300
